version: "3.8"
services:
  mongo:
    image: mongo:5
    container_name: chat-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - CHAT_SERVICE_URL=http://chat-service:3002
      - NOTIFICATION_SERVICE_URL=http://notification-service:3003
      - FILE_SERVICE_URL=http://file-service:3004
    ports:
      - "3000:3000"

  user-service:
    build: ./user-service
    container_name: chat-app-user-service
    env_file:
      - ./user-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  chat-service:
    build: ./chat-service
    container_name: chat-app-chat-service
    env_file:
      - ./chat-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongo

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    environment:
      - PORT=3003
      - REDIS_URL=redis://redis:6379
    ports:
      - "3003:3003"
    depends_on:
      - redis

  file-service:
    build:
      context: ./file-service
      dockerfile: Dockerfile
    container_name: file-service
    environment:
      - PORT=3004
      - FRONTEND_ORIGIN=http://localhost:3000
      - MINIO_ENDPOINT=http://minio:9000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - AWS_BUCKET_NAME=uploads
    ports:
      - "3004:3004"
    volumes:
      - ./file-service/uploads:/app/uploads
    depends_on:
      - minio

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
  minio-data:
  redis_data:
